'use strict';
const KEY='money-until-payday-v1'; // Retain the storage key so existing installs migrate in place.
const DEFAULT_CATEGORIES=['Food/Coffee','Entertainment','Shopping','Transport','Other'];
const $=id=>document.getElementById(id);
const currencyFor=p=>p?.currency||active()?.currency||state.settings.currency;
const money=(cents,p)=>new Intl.NumberFormat(currencyFor(p)==='USD'?'en-US':'en-CA',{style:'currency',currency:currencyFor(p),currencyDisplay:'code'}).format(cents/100);
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today=()=>localDate(new Date());
const dateUTC=s=>Date.parse(s+'T00:00:00Z');
const shift=(s,n)=>new Date(dateUTC(s)+n*86400000).toISOString().slice(0,10);
const daysBetween=(a,b)=>Math.round((dateUTC(b)-dateUTC(a))/86400000);
const inPeriod=(p,s)=>s>=p.startDate&&s<p.nextPayday;
const sum=p=>state.transactions.filter(t=>t.payPeriodId===p.id&&inPeriod(p,t.transactionDate.slice(0,10))).reduce((n,t)=>n+t.amountCents,0);
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const initial=()=>({version:5,streakBadges:[],finishers:[],dailyCheckins:[],allocations:[],settings:{defaultAllowanceCents:null,paydayCadenceDays:14,currency:'CAD',categories:[...DEFAULT_CATEGORIES]},periods:[],transactions:[],noSpendDays:[]});
let state=initial(),installPrompt=null,noticeTimer;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{flash('Storage is full or blocked. Export a backup and check browser settings.',true);return false}}
function active(){return state.periods.find(p=>p.status==='active')}
function amountCents(raw){if(!/^\d+(?:\.\d{1,2})?$/.test(String(raw).trim()))return NaN;return Math.round(Number(raw)*100)}
function dateValid(s){return /^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(dateUTC(s))&&new Date(dateUTC(s)).toISOString().slice(0,10)===s}
function flash(msg,error=false){const n=$('notice');n.textContent=msg;n.classList.toggle('error',error);n.hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.hidden=true,5500)}
function node(tag,text,cls){let e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function empty(el,text){el.replaceChildren(node('div',text,'empty'))}
function setView(v){if(v==='transactions'&&!active())v='dashboard';document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==v);document.querySelectorAll('.nav button').forEach(e=>e.setAttribute('aria-current',e.dataset.view===v?'page':'false'));window.scrollTo(0,0)}
function formatDate(s){return new Date(dateUTC(s)).toLocaleDateString('en-CA',{timeZone:'UTC',month:'short',day:'numeric',year:'numeric'})}
function allocationTotal(p,kind){return state.allocations.filter(x=>x.payPeriodId===p.id&&x.kind===kind).reduce((n,x)=>n+x.amountCents,0)}
function render(){const p=active(),now=today();document.querySelectorAll('.currency-code').forEach(el=>el.textContent=currencyFor(p));$('setup').hidden=!!p;$('active').hidden=!p;
 if(p){renderAllocations(p);let spent=sum(p),remaining=p.startingAllowanceCents-spent,days=Math.max(1,daysBetween(now,p.nextPayday));$('period-label').textContent=`${formatDate(p.startDate)} – ${formatDate(p.nextPayday)} · Current period`;$('remaining').textContent=money(Math.max(0,remaining));$('budget-state').textContent=remaining<0?`${money(-remaining)} over budget`:remaining===0?'Allowance fully spent':'Available to spend';$('budget-state').classList.toggle('over',remaining<0);$('safe').textContent=money(Math.max(0,Math.floor(remaining/days)));$('days').textContent=daysBetween(now,p.nextPayday)>0?`${daysBetween(now,p.nextPayday)} ${daysBetween(now,p.nextPayday)===1?'day':'days'}`:'Payday reached';$('spent-label').textContent=`${money(spent)} spent of ${money(p.startingAllowanceCents)}`;let pct=Math.round(spent/p.startingAllowanceCents*100);$('progress-label').textContent=`${pct}% used`; $('allowance-left').textContent=remaining>=0?`${money(remaining)} left of ${money(p.startingAllowanceCents)}`:`${money(-remaining)} over the ${money(p.startingAllowanceCents)} allowance`; $('allowance-track').setAttribute('aria-valuenow',String(Math.min(100,pct))); $('allowance-track').setAttribute('aria-valuetext',`${money(spent)} spent of ${money(p.startingAllowanceCents)}${remaining<0?`, ${money(-remaining)} over budget`:''}`);$('progress').style.width=`${Math.min(100,pct)}%`;$('progress').classList.toggle('over',pct>100);
 let discretionary=state.transactions.filter(t=>t.payPeriodId===p.id);renderCheckins(p,now);
 let tx=discretionary.sort((a,b)=>b.transactionDate.localeCompare(a.transactionDate));renderTransactions($('recent'),tx.slice(0,3),false);renderTransactions($('transaction-list'),tx,true);$('transaction-summary').textContent=`${tx.length} ${tx.length===1?'purchase':'purchases'} · ${money(spent)} spent`;}
 renderHistory();renderMilestones();$('settings-form').elements.defaultAllowance.value=state.settings.defaultAllowanceCents===null?'':(state.settings.defaultAllowanceCents/100).toFixed(2);$('settings-form').elements.paydayCadenceDays.value=state.settings.paydayCadenceDays;$('settings-form').elements.currency.value=state.settings.currency;}
const MILESTONES=[[1,'First Day','icons/badge-1-day-bronze.png'],[3,'First Spark','icons/badge-3-day-bronze.png'],[7,'Finding Rhythm','icons/badge-7-day-silver.png'],[10,'Double Digits','icons/badge-10-day-silver.png'],[14,'Full Stride','icons/badge-14-day-gold.png'],[30,'Month of Momentum','icons/badge-30-day-platinum-bar.png']];
function checkinRecord(p,date){return state.noSpendDays.find(n=>n.payPeriodId===p.id&&n.date===date)||state.dailyCheckins.find(c=>c.payPeriodId===p.id&&c.date===date)}
function dayStatus(p,date){let record=checkinRecord(p,date);if(!record)return 'pending';if(record.onTime===false)return 'late';return state.noSpendDays.includes(record)?'no-spend':'logged'}
function checkinStats(p){let checked=0,gold=0,onTime=0,total=daysBetween(p.startDate,p.nextPayday);for(let i=0;i<total;i++){let status=dayStatus(p,shift(p.startDate,i));if(status!=='pending')checked++;if(status==='no-spend')gold++;if(status==='logged'||status==='no-spend')onTime++}return {checked,gold,onTime,total}}
function timelyDates(){let dates=new Set();for(const p of state.periods){for(let date=p.startDate;date<p.nextPayday&&date<=today();date=shift(date,1)){if(['logged','no-spend'].includes(dayStatus(p,date)))dates.add(date)}}return dates}
function streakAt(date,dates=timelyDates()){let count=0;for(let d=date;dates.has(d);d=shift(d,-1))count++;return count}
function currentStreak(){let dates=timelyDates(),now=today();return streakAt(dates.has(now)?now:shift(now,-1),dates)}
function awardStreaks(date){let count=streakAt(date);let earned=[];for(const [days,name] of MILESTONES){if(count>=days&&!state.streakBadges.some(b=>b.days===days)){state.streakBadges.push({days,earnedAt:new Date().toISOString()});earned.push(name)}}return earned}
function renderMilestones(){let count=currentStreak();$('current-streak').textContent=`${count} day${count===1?'':'s'} current`;let grid=$('milestone-grid'),heading=grid.parentElement.querySelector('.row h2'),intro=grid.previousElementSibling;if(heading)heading.textContent='Achievements';if(intro?.tagName==='P')intro.remove();grid.classList.add('achievement-grid');grid.replaceChildren();for(const [days,name,asset] of MILESTONES){let earned=state.streakBadges.some(b=>b.days===days),tile=node('div',undefined,`achievement ${earned?'is-unlocked':'is-locked'}${days===14?' achievement-featured-gold':''}${days===30?' achievement-platinum':''}`),image=document.createElement('img');image.src=asset;image.alt=`${days}-day on-time streak achievement, ${earned?'earned':'locked'}`;image.loading='lazy';tile.append(image);grid.append(tile)}for(const id of ['finisher-collection','history-finishers']){let box=$(id);box.replaceChildren();let badges=[...state.finishers].sort((a,b)=>b.earnedAt.localeCompare(a.earnedAt));if(!badges.length){empty(box,'No completed on-time pay period yet.');continue}for(const badge of badges){let p=state.periods.find(x=>x.id===badge.periodId),row=node('div',undefined,'finisher-item'),desc=node('div');desc.append(node('strong','Payday Finisher'),node('div',p?`${formatDate(p.startDate)} – ${formatDate(p.nextPayday)}`:'Pay period completed','muted small'));row.append(node('span','✦','finisher-coin'),desc);box.append(row)}}}
function renderCheckins(p,now){const picker=$('no-spend-date'),grid=$('day-grid');picker.min=p.startDate;picker.max=now<p.nextPayday?now:shift(p.nextPayday,-1);if(!picker.value||picker.value>picker.max||picker.value<p.startDate)picker.value=picker.max>=p.startDate?picker.max:'';grid.replaceChildren();const total=daysBetween(p.startDate,p.nextPayday);for(let i=0;i<total;i++){let date=shift(p.startDate,i),status=dayStatus(p,date),future=date>now,button=node('button',String(i+1),'day-tile '+(future?'future':status)+(date===picker.value?' selected':''));button.type='button';button.disabled=future;button.title=`${formatDate(date)}: ${future?'upcoming':status==='no-spend'?'no spend confirmed on time':status==='logged'?'purchases logged on time':status==='late'?'checked in later':'not checked in'}`;button.setAttribute('aria-label',button.title);button.append(node('small',date.slice(5)));if(!future)button.addEventListener('click',()=>{picker.value=date;renderCheckins(p,today())});grid.append(button)}const stats=checkinStats(p);$('checkin-count').textContent=`${stats.checked} of ${stats.total} checked · ${stats.onTime} on time`;$('mark-logged').disabled=!picker.value;$('clear-day').disabled=!picker.value||dayStatus(p,picker.value)==='pending';$('mark-day').disabled=!picker.value;const hasPurchases=state.transactions.some(t=>t.payPeriodId===p.id&&t.transactionDate.slice(0,10)===picker.value),status=dayStatus(p,picker.value);$('mark-help').textContent=!picker.value?'No day to close out yet.':`Selected: ${formatDate(picker.value)} · ${status==='no-spend'?'No-spend confirmed on time.':status==='logged'?'Purchases confirmed on time.':status==='late'?'Caught up later.':'Unchecked.'}${hasPurchases?' This day has purchases.':''} A purchase added later clears that day’s confirmation.`}
function renderTransactions(el,tx,actions){el.replaceChildren();if(!tx.length){empty(el,'No purchases logged yet.');return}for(const t of tx){const row=node('div',undefined,'item'),main=node('div',undefined,'item-main'),side=node('div',undefined,'item-side');main.append(node('div',t.category,'item-title'),node('div',`${formatDate(t.transactionDate.slice(0,10))}${t.note?' · '+t.note:''}`,'item-sub'));side.append(node('div',money(t.amountCents),'item-title'));if(actions){let group=node('div',undefined,'item-actions');for(let [label,fn] of [['Edit',()=>openPurchase(t)],['Delete',()=>deletePurchase(t)]]){let b=node('button',label,'text-button');b.type='button';b.addEventListener('click',fn);group.append(b)}side.append(group)}row.append(main,side);el.append(row)}}
function renderHistory(){let list=$('history-list');list.replaceChildren();let closed=state.periods.filter(p=>p.status==='closed').sort((a,b)=>b.startDate.localeCompare(a.startDate));if(!closed.length){empty(list,'Closed pay periods will appear here.');return}for(let p of closed){let spent=sum(p),remaining=p.startingAllowanceCents-spent,card=node('article',undefined,'card history-card');card.append(node('h2',`${formatDate(p.startDate)} – ${formatDate(p.nextPayday)}`),node('div',`${money(spent,p)} discretionary spent · ${remaining>=0?money(remaining,p)+' remaining':money(-remaining,p)+' over budget'}`));let plan=node('div',`${p.payAmountCents===null?'Paycheque not recorded':money(p.payAmountCents,p)+' paycheque'} · ${money(allocationTotal(p,'must'),p)} must pays · ${money(allocationTotal(p,'debt'),p)} debt · ${money(allocationTotal(p,'savings'),p)} savings`,'item-sub');card.append(plan);let checked=checkinStats(p);card.append(node('div',`${checked.checked} of ${checked.total} days checked in · ${checked.onTime} on time${state.finishers.some(b=>b.periodId===p.id)?' · Payday Finisher earned':''}`,'item-sub'));let totals={};for(const t of state.transactions.filter(t=>t.payPeriodId===p.id))totals[t.category]=(totals[t.category]||0)+t.amountCents;let box=node('div',undefined,'breakdown');for(const [category,cents] of Object.entries(totals).sort((a,b)=>b[1]-a[1])){let r=node('div',undefined,'row');r.append(node('span',category),node('strong',money(cents,p)));box.append(r)}if(!box.children.length)box.append(node('span','No purchases'));card.append(box);list.append(card)}}
const ALLOCATION_LABEL={must:'Must pay',debt:'Debt payment',savings:'Savings transfer'};
function renderAllocations(p){
 $('pay-amount').textContent=p.payAmountCents===null?'Pay amount missing':money(p.payAmountCents);
 let breakdown=$('allocation-summary');breakdown.replaceChildren();for(const kind of ['must','debt','savings']){let r=node('div',undefined,'row');r.append(node('span',kind==='must'?'Must pays':kind==='debt'?'Debt payments':'Savings'),node('strong',money(allocationTotal(p,kind))));breakdown.append(r);let list=$(kind+'-list');list.replaceChildren();let entries=state.allocations.filter(a=>a.payPeriodId===p.id&&a.kind===kind);if(!entries.length){empty(list,'Nothing recorded yet.');continue}for(const a of entries){let item=node('div',undefined,'item'),main=node('div',a.reason,'item-main'),side=node('div',undefined,'item-side');side.append(node('strong',money(a.amountCents)));let actions=node('div',undefined,'item-actions');for(const [label,fn] of [['Edit',()=>openAllocation(kind,a)],['Delete',()=>deleteAllocation(a)]]){let button=node('button',label,'text-button');button.type='button';button.addEventListener('click',fn);actions.append(button)}side.append(actions);item.append(main,side);list.append(item)}}
 let unallocated=p.payAmountCents===null?null:p.payAmountCents-p.startingAllowanceCents-['must','debt','savings'].reduce((n,k)=>n+allocationTotal(p,k),0);$('unallocated').previousElementSibling.textContent='Unallocated balance';$('unallocated').textContent=unallocated===null?'—':money(unallocated);$('unallocated').classList.toggle('negative',unallocated!==null&&unallocated<0);
 renderPayPie(p,unallocated);
}
function renderPayPie(p,unallocated){
 const pie=$('pay-pie'),legend=$('pie-legend');legend.replaceChildren();
 if(p.payAmountCents===null){pie.style.background='var(--panel2)';pie.setAttribute('aria-label','Paycheque chart unavailable until a pay amount is entered');legend.append(node('span','Enter your pay amount to see the chart.','muted small'));return}
 const parts=[['Must pays',allocationTotal(p,'must'),'#638fe6'],['Debt',allocationTotal(p,'debt'),'#b98bf0'],['Savings',allocationTotal(p,'savings'),'#69c7af'],['Discretionary',p.startingAllowanceCents,'#ec9377'],['Unallocated',Math.max(0,unallocated),'#8a9aab']];
 // When assigned amounts exceed pay, show their relative shares and state the excess separately.
 const total=parts.reduce((n,x)=>n+x[1],0),stops=[];let at=0;for(const [label,cents,color] of parts){if(cents>0){let end=at+cents/total*100;stops.push(`${color} ${at}% ${end}%`);at=end}let row=node('div',undefined,'legend-row'),dot=node('span',undefined,'legend-dot'),info=node('div',undefined,'legend-text');dot.style.background=color;info.append(node('span',label),node('strong',money(cents)));row.append(dot,info);legend.append(row)}pie.style.background=`conic-gradient(${stops.join(',')})`;pie.setAttribute('aria-label',`Paycheque plan: ${parts.map(([label,cents])=>`${label} ${money(cents)}`).join(', ')}${unallocated<0?`; ${money(-unallocated)} overallocated`:''}`);
 if(unallocated<0)legend.append(node('strong',`${money(-unallocated)} overallocated`,'negative small'));
}
function openAllocation(kind,a){if(!active())return;let f=$('allocation-form');f.reset();f.elements.id.value=a?.id||'';f.elements.kind.value=kind;f.elements.amount.value=a?(a.amountCents/100).toFixed(2):'';f.elements.reason.value=a?.reason||'';$('allocation-title').textContent=a?'Edit '+ALLOCATION_LABEL[kind]:'Add '+ALLOCATION_LABEL[kind];$('reason-label').firstChild.textContent=kind==='debt'?'Which debt?':kind==='savings'?'Savings destination':'Reason';$('allocation-error').textContent='';$('allocation-dialog').showModal();setTimeout(()=>f.elements.amount.focus(),30)}
function deleteAllocation(a){if(!confirm(`Delete ${money(a.amountCents)} for ${a.reason}?`))return;state.allocations=state.allocations.filter(x=>x.id!==a.id);persist();render();flash('Entry deleted.')}
$('allocation-form').addEventListener('submit',e=>{e.preventDefault();let p=active(),f=e.currentTarget.elements,kind=f.kind.value,cents=amountCents(f.amount.value),reason=f.reason.value.trim(),id=f.id.value;if(!p||!ALLOCATION_LABEL[kind]||!Number.isSafeInteger(cents)||cents<1||!reason||reason.length>100){$('allocation-error').textContent='Enter a positive amount and a reason.';return}let old=id?state.allocations.find(a=>a.id===id&&a.payPeriodId===p.id):null;if(id&&!old)return;let entry={id:old?.id||uid(),payPeriodId:p.id,kind,amountCents:cents,reason,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(old)Object.assign(old,entry);else state.allocations.push(entry);persist();$('allocation-dialog').close();render();flash('Entry saved.')});
document.querySelectorAll('.allocation-add').forEach(b=>b.addEventListener('click',()=>openAllocation(b.dataset.kind)));
$('edit-pay').addEventListener('click',()=>{let p=active();if(!p)return;$('pay-form').elements.amount.value=p.payAmountCents===null?'':(p.payAmountCents/100).toFixed(2);$('pay-dialog').showModal()});
$('pay-form').addEventListener('submit',e=>{e.preventDefault();let p=active(),cents=amountCents(e.currentTarget.elements.amount.value);if(!p||!Number.isSafeInteger(cents)||cents<1)return;p.payAmountCents=cents;persist();$('pay-dialog').close();render();flash('Paycheque updated.')});
for(const [id,dialog] of [['[data-allocation-close]','allocation-dialog'],['[data-pay-close]','pay-dialog']])document.querySelector(id).addEventListener('click',()=>$(dialog).close());
function openPurchase(t){let p=active();if(!p)return;const form=$('purchase-form');form.reset();form.elements.id.value=t?.id||'';form.elements.amount.value=t?(t.amountCents/100).toFixed(2):'';const sel=form.elements.category;sel.replaceChildren(...state.settings.categories.map(c=>{let o=node('option',c);o.value=c;return o}));sel.value=t?.category||state.transactions.filter(x=>x.payPeriodId===p.id).at(-1)?.category||state.settings.categories[0];const d=new Date(),localNow=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);form.elements.transactionDate.value=t?.transactionDate||localNow;form.elements.note.value=t?.note||'';$('purchase-title').textContent=t?'Edit purchase':'Add purchase';$('purchase-error').textContent='';$('purchase-dialog').showModal();setTimeout(()=>form.elements.amount.focus(),30)}
function deletePurchase(t){if(!confirm(`Delete ${money(t.amountCents)} in ${t.category}?`))return;state.transactions=state.transactions.filter(x=>x.id!==t.id);persist();render();flash('Purchase deleted.')}
function validateBackup(s){
 if(!s||![1,2,3,4,5].includes(s.version)||!s.settings||!Array.isArray(s.periods)||!Array.isArray(s.transactions)||!Array.isArray(s.noSpendDays)||s.version>=2&&!Array.isArray(s.allocations)||s.version>=3&&!Array.isArray(s.dailyCheckins)||s.version>=4&&(!Array.isArray(s.streakBadges)||!Array.isArray(s.finishers)))throw Error('Unsupported or incomplete backup.');
 const q=s.settings;if(q.defaultAllowanceCents!==null&&(!Number.isSafeInteger(q.defaultAllowanceCents)||q.defaultAllowanceCents<1)||!Number.isInteger(q.paydayCadenceDays)||q.paydayCadenceDays<1||q.paydayCadenceDays>366||!['CAD','USD'].includes(q.currency)||!Array.isArray(q.categories)||!q.categories.length||q.categories.some(c=>typeof c!=='string'||!c||c.length>60))throw Error('Invalid settings in backup.');
 let ids=new Set(),act=0;for(const p of s.periods){if(typeof p.id!=='string'||ids.has(p.id)||!dateValid(p.startDate)||!dateValid(p.nextPayday)||p.nextPayday<=p.startDate||!Number.isSafeInteger(p.startingAllowanceCents)||p.startingAllowanceCents<1||!['active','closed'].includes(p.status)||s.version===5&&!['CAD','USD'].includes(p.currency)||s.version>=2&&p.payAmountCents!==null&&(!Number.isSafeInteger(p.payAmountCents)||p.payAmountCents<1))throw Error('Invalid pay period in backup.');ids.add(p.id);act+=p.status==='active'}if(act>1)throw Error('Backup contains multiple active periods.');
 let txIds=new Set();for(const t of s.transactions){if(typeof t.id!=='string'||txIds.has(t.id)||!ids.has(t.payPeriodId)||!Number.isSafeInteger(t.amountCents)||t.amountCents<1||typeof t.category!=='string'||!q.categories.includes(t.category)||typeof t.transactionDate!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(t.transactionDate)||Number.isNaN(new Date(t.transactionDate).getTime())||typeof t.note!=='string'||t.note.length>200||!inPeriod(s.periods.find(p=>p.id===t.payPeriodId),t.transactionDate.slice(0,10)))throw Error('Invalid purchase in backup.');txIds.add(t.id)}
 for(const n of s.noSpendDays){let p=s.periods.find(p=>p.id===n.payPeriodId);if(!p||!dateValid(n.date)||!inPeriod(p,n.date)||n.date>(s.version>=4?today():shift(today(),-1))||s.transactions.some(t=>t.payPeriodId===p.id&&t.transactionDate.slice(0,10)===n.date))throw Error('Invalid no-spend day in backup.')}
 const allocations=s.version>=2?s.allocations:[],allocationIds=new Set();for(const a of allocations){if(typeof a.id!=='string'||allocationIds.has(a.id)||!ids.has(a.payPeriodId)||!['must','debt','savings'].includes(a.kind)||!Number.isSafeInteger(a.amountCents)||a.amountCents<1||typeof a.reason!=='string'||!a.reason.trim()||a.reason.length>100)throw Error('Invalid allocation in backup.');allocationIds.add(a.id)}
 let checkins=s.version>=3?s.dailyCheckins:[],keys=new Set();for(const c of checkins){let period=s.periods.find(p=>p.id===c.payPeriodId),key=c.payPeriodId+'|'+c.date;if(!period||!dateValid(c.date)||!inPeriod(period,c.date)||c.date>today()||keys.has(key)||s.noSpendDays.some(n=>n.payPeriodId===c.payPeriodId&&n.date===c.date))throw Error('Invalid daily check-in in backup.');keys.add(key)}
 let noSpendDays=s.noSpendDays;if(s.version>=4){for(const r of [...noSpendDays,...checkins])if(typeof r.onTime!=='boolean'||typeof r.confirmedAt!=='string'||Number.isNaN(Date.parse(r.confirmedAt)))throw Error('Invalid check-in status in backup.')}else{const localConfirmed=r=>{let d=new Date(r.confirmedAt);return Number.isNaN(d.getTime())?'':localDate(d)};noSpendDays=noSpendDays.map(r=>({...r,onTime:[r.date,shift(r.date,1)].includes(localConfirmed(r))}));checkins=checkins.map(r=>({...r,onTime:localConfirmed(r)===r.date}))}
 const streakBadges=s.version>=4?s.streakBadges:[],finishers=s.version>=4?s.finishers:[];let milestones=new Set();for(const b of streakBadges){if(!b||!MILESTONES.some(([days])=>days===b.days)||milestones.has(b.days)||typeof b.earnedAt!=='string'||Number.isNaN(Date.parse(b.earnedAt)))throw Error('Invalid milestone in backup.');milestones.add(b.days)}let completed=new Set();for(const b of finishers){if(!b||typeof b.periodId!=='string'||completed.has(b.periodId)||!s.periods.some(p=>p.id===b.periodId&&p.status==='closed')||typeof b.earnedAt!=='string'||Number.isNaN(Date.parse(b.earnedAt)))throw Error('Invalid Payday Finisher in backup.');completed.add(b.periodId)}
 return {version:5,settings:q,periods:s.periods.map(p=>({...p,currency:s.version===5?p.currency:'CAD',payAmountCents:s.version===1?null:p.payAmountCents})),transactions:s.transactions,noSpendDays,allocations,dailyCheckins:checkins,streakBadges,finishers};
}
function download(filename,content,type){let url=URL.createObjectURL(new Blob([content],{type}));let a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
function csvCell(v){return '"'+String(v??'').replace(/^[=+\-@\t\r]/,'\'$&').replaceAll('"','""')+'"'}
function exportCSV(){let head=['Date/time','Amount','Currency','Category','Note','Pay period ID','Pay period label'];let rows=state.transactions.map(t=>{let p=state.periods.find(x=>x.id===t.payPeriodId);return [t.transactionDate,(t.amountCents/100).toFixed(2),currencyFor(p),t.category,t.note,p.id,`${p.startDate} to ${p.nextPayday}`]});download(`money-until-payday-transactions-${today()}.csv`,'\ufeff'+[head,...rows].map(row=>row.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8')}
$('period-form').addEventListener('submit',e=>{e.preventDefault();let f=e.currentTarget.elements,start=f.startDate.value,end=f.nextPayday.value,cents=amountCents(f.allowance.value),pay=amountCents(f.payAmount.value);if(!Number.isSafeInteger(pay)||pay<1||active()||!dateValid(start)||!dateValid(end)||end<=start||end<=today()||start>today()||!Number.isSafeInteger(cents)||cents<1){flash('Use a start date on or before today, a future payday, and a positive allowance.',true);return}state.periods.push({id:uid(),startDate:start,nextPayday:end,startingAllowanceCents:cents,payAmountCents:pay,currency:state.settings.currency,status:'active',createdAt:new Date().toISOString(),closedAt:null});persist();render();flash('Pay period started.')});
$('purchase-form').addEventListener('submit',e=>{e.preventDefault();let p=active(),f=e.currentTarget.elements,cents=amountCents(f.amount.value),stamp=f.transactionDate.value,date=stamp.slice(0,10),id=f.id.value;if(!p||!Number.isSafeInteger(cents)||cents<1||!dateValid(date)||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(stamp)||Number.isNaN(new Date(stamp).getTime())||!inPeriod(p,date)||date>today()||!state.settings.categories.includes(f.category.value)){$('purchase-error').textContent=`Enter a valid amount and a date between ${p?.startDate||'the start'} and the earlier of today or the day before payday.`;return}let t=id?state.transactions.find(x=>x.id===id&&x.payPeriodId===p.id):null;if(id&&!t)return;let next={id:t?.id||uid(),payPeriodId:p.id,amountCents:cents,category:f.category.value,transactionDate:stamp,note:f.note.value.trim(),createdAt:t?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(t)Object.assign(t,next);else state.transactions.push(next);state.noSpendDays=state.noSpendDays.filter(n=>!(n.payPeriodId===p.id&&n.date===date));state.dailyCheckins=state.dailyCheckins.filter(n=>!(n.payPeriodId===p.id&&n.date===date));persist();$('purchase-dialog').close();render();setView('dashboard');navigator.vibrate?.(20);flash(t?'Purchase updated.':'Purchase saved.')});
function closeDay(kind){let p=active(),date=$('no-spend-date').value;if(!p||!dateValid(date)||!inPeriod(p,date)||date>today())return;let purchases=state.transactions.some(t=>t.payPeriodId===p.id&&t.transactionDate.slice(0,10)===date);if(kind==='no-spend'&&purchases){flash('This day has a purchase; confirm purchases logged instead.',true);return}state.noSpendDays=state.noSpendDays.filter(x=>!(x.payPeriodId===p.id&&x.date===date));state.dailyCheckins=state.dailyCheckins.filter(x=>!(x.payPeriodId===p.id&&x.date===date));let onTime=date===today(),record={date,payPeriodId:p.id,confirmedAt:new Date().toISOString(),onTime};if(kind==='no-spend')state.noSpendDays.push(record);else state.dailyCheckins.push(record);let earned=onTime?awardStreaks(date):[];persist();render();flash(`${onTime?(kind==='no-spend'?'Gold day recorded.':'Blue day recorded.'):'Catch-up day recorded in purple.'}${earned.length?' Milestone: '+earned.join(', ')+'.':''}`)} 
$('mark-day').addEventListener('click',()=>closeDay('no-spend'));$('mark-logged').addEventListener('click',()=>closeDay('logged'));$('clear-day').addEventListener('click',()=>{let p=active(),date=$('no-spend-date').value;if(!p||!inPeriod(p,date))return;state.noSpendDays=state.noSpendDays.filter(x=>!(x.payPeriodId===p.id&&x.date===date));state.dailyCheckins=state.dailyCheckins.filter(x=>!(x.payPeriodId===p.id&&x.date===date));persist();render();flash('Check-in cleared.')});$('no-spend-date').addEventListener('change',()=>{let p=active();if(p)renderCheckins(p,today())});
$('what-if').addEventListener('click',()=>{if(!active())return;let f=$('preview-form');f.reset();$('preview-result').textContent='Enter an amount to see its effect.';$('preview-add').disabled=true;$('preview-dialog').showModal();setTimeout(()=>f.elements.amount.focus(),30)});
$('preview-form').elements.amount.addEventListener('input',e=>{let p=active(),cents=amountCents(e.target.value);if(!p||!Number.isSafeInteger(cents)||cents<1){$('preview-result').textContent='Enter a positive amount to preview.';$('preview-add').disabled=true;return}let left=p.startingAllowanceCents-sum(p)-cents,days=Math.max(1,daysBetween(today(),p.nextPayday));$('preview-result').textContent=`If you spend ${money(cents)}: ${left>=0?money(left)+' left':money(-left)+' over budget'} · ${money(Math.max(0,Math.floor(left/days)))} safe per day. Nothing has been recorded.`;$('preview-add').disabled=false});
$('preview-add').addEventListener('click',()=>{let amount=$('preview-form').elements.amount.value;$('preview-dialog').close();openPurchase();$('purchase-form').elements.amount.value=amount});document.querySelector('[data-preview-close]').addEventListener('click',()=>$('preview-dialog').close());
$('close-period').addEventListener('click',()=>{let p=active();if(!p)return;let rem=p.startingAllowanceCents-sum(p),stats=checkinStats(p),box=$('recap-content');box.replaceChildren();for(const [label,value] of [['Discretionary result',rem>=0?`${money(rem)} remaining`:`${money(-rem)} over budget`],['Days accounted for',`${stats.checked} of ${stats.total}`],['On-time check-ins',`${stats.onTime} of ${stats.total}`],['No-spend days',`${stats.gold}`],['Sent to debt',money(allocationTotal(p,'debt'))],['Sent to savings',money(allocationTotal(p,'savings'))]]){let r=node('div',undefined,'row');r.append(node('span',label),node('strong',value));box.append(r)}$('recap-badge').textContent=stats.onTime===stats.total?'Every day was checked in on time. Payday Finisher will be added to your collection.':'Payday Finisher needs every day checked in on the day it happened.';$('recap-dialog').showModal()});
$('confirm-close').addEventListener('click',()=>{let p=active();if(!p)return;p.status='closed';p.closedAt=new Date().toISOString();let earned=checkinStats(p).onTime===checkinStats(p).total&&!state.finishers.some(b=>b.periodId===p.id);if(earned)state.finishers.push({periodId:p.id,earnedAt:new Date().toISOString()});persist();$('recap-dialog').close();render();prefillPeriod();flash(earned?'Payday Finisher earned and saved. Enter your next paycheque to continue.':'Pay period archived. Enter your next paycheque to continue.')});document.querySelector('[data-recap-close]').addEventListener('click',()=>$('recap-dialog').close());
$('settings-form').elements.currency.addEventListener('change',e=>{if(e.target.value!==state.settings.currency)$('settings-form').elements.defaultAllowance.value=''});
$('settings-form').addEventListener('submit',e=>{e.preventDefault();let f=e.currentTarget.elements,c=f.defaultAllowance.value.trim()===''?null:amountCents(f.defaultAllowance.value),d=Number(f.paydayCadenceDays.value),currency=f.currency.value;if(!['CAD','USD'].includes(currency)||c!==null&&(!Number.isSafeInteger(c)||c<1)||!Number.isInteger(d)||d<1||d>366){flash('Enter an optional positive allowance and a cadence from 1 to 366 days.',true);return}state.settings.defaultAllowanceCents=c;state.settings.paydayCadenceDays=d;state.settings.currency=currency;persist();render();flash('Defaults saved.')});
$('export-json').addEventListener('click',()=>download(`money-until-payday-backup-${today()}.json`,JSON.stringify(state,null,2),'application/json'));
$('export-csv').addEventListener('click',exportCSV);
$('export-allocations').addEventListener('click',()=>{let rows=state.allocations.map(a=>{let p=state.periods.find(x=>x.id===a.payPeriodId);return [a.kind,(a.amountCents/100).toFixed(2),currencyFor(p),a.reason,p.id,`${p.startDate} to ${p.nextPayday}`]});download(`money-until-payday-allocations-${today()}.csv`,'\ufeff'+[['Type','Amount','Currency','Reason / debt','Pay period ID','Pay period label'],...rows].map(row=>row.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8')});
$('import-json').addEventListener('change',async e=>{let file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>10*1024*1024){flash('Backup is larger than 10 MB.',true);return}try{let imported=validateBackup(JSON.parse(await file.text()));if(!confirm('Replace all current periods, purchases, and settings with this backup? Export your current data first if needed.'))return;let old=state;state=imported;if(!persist()){state=old;return}render();setView('dashboard');prefillPeriod();flash('Backup restored.')}catch(err){flash(err.message||'Could not read backup.',true)}});
function prefillPeriod(){if(active())return;let last=state.periods.at(-1),start=last&&last.nextPayday<=today()?last.nextPayday:today();let next=last&&last.nextPayday>today()?last.nextPayday:shift(start,state.settings.paydayCadenceDays);if(next<=today())next=shift(today(),state.settings.paydayCadenceDays);let f=$('period-form').elements;f.startDate.value=start;f.nextPayday.value=next;f.allowance.value=state.settings.defaultAllowanceCents===null?'':(state.settings.defaultAllowanceCents/100).toFixed(2);f.payAmount.value=last?.payAmountCents&&currencyFor(last)===state.settings.currency? (last.payAmountCents/100).toFixed(2):''}
$('add').addEventListener('click',()=>openPurchase());document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelector('[data-close]').addEventListener('click',()=>$('purchase-dialog').close());$('purchase-dialog').addEventListener('click',e=>{if(e.target===$('purchase-dialog'))e.target.close()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').hidden=false});$('install').addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('install').hidden=true});window.addEventListener('appinstalled',()=>$('install').hidden=true);
try{let raw=localStorage.getItem(KEY);if(raw){state=validateBackup(JSON.parse(raw));if(JSON.parse(raw).version<5)persist()}}catch{state=initial();flash('Saved data could not be read. Export any older backup before entering new data.',true)}
render();prefillPeriod();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
